#!/usr/bin/env perl

use utf8;
use strict;
use warnings;
use experimental qw(try smartmatch);

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('CharmBoard');

__END__
